// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTceog5hf7f5dLEtX4VVlYE9o2qlvFhPc',
    appId: '1:667772071153:web:f2171a9f69d006c0204d50',
    messagingSenderId: '667772071153',
    projectId: 'daily-routine-planner-96af5',
    authDomain: 'daily-routine-planner-96af5.firebaseapp.com',
    storageBucket: 'daily-routine-planner-96af5.firebasestorage.app',
    measurementId: 'G-48LVTE4PXD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCo0JOkoZ3sGjhLoEN__sAHrWcFjFQTacs',
    appId: '1:667772071153:android:51a83d89b979c080204d50',
    messagingSenderId: '667772071153',
    projectId: 'daily-routine-planner-96af5',
    storageBucket: 'daily-routine-planner-96af5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5MTJ3kgx0CZmPUpeoCoAlyTegBs51Bgc',
    appId: '1:667772071153:ios:6f70552757897e6b204d50',
    messagingSenderId: '667772071153',
    projectId: 'daily-routine-planner-96af5',
    storageBucket: 'daily-routine-planner-96af5.firebasestorage.app',
    iosBundleId: 'com.example.dailyRoutinePlanner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5MTJ3kgx0CZmPUpeoCoAlyTegBs51Bgc',
    appId: '1:667772071153:ios:6f70552757897e6b204d50',
    messagingSenderId: '667772071153',
    projectId: 'daily-routine-planner-96af5',
    storageBucket: 'daily-routine-planner-96af5.firebasestorage.app',
    iosBundleId: 'com.example.dailyRoutinePlanner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCTceog5hf7f5dLEtX4VVlYE9o2qlvFhPc',
    appId: '1:667772071153:web:c32034762bedce91204d50',
    messagingSenderId: '667772071153',
    projectId: 'daily-routine-planner-96af5',
    authDomain: 'daily-routine-planner-96af5.firebaseapp.com',
    storageBucket: 'daily-routine-planner-96af5.firebasestorage.app',
    measurementId: 'G-HDL33MBECQ',
  );
}
